import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#262626',
        'on-background': '#ffffff',
        'on-secondary-fixed-variant': '#5c5b5b',
        'on-error': '#450900',
        'error-dim': '#d53d18',
        'surface-container-high': '#20201f',
        'outline-variant': '#484847',
        secondary: '#e5e2e1',
        'on-primary': '#655400',
        'on-surface': '#ffffff',
        'secondary-dim': '#d6d4d3',
        'surface-container-lowest': '#000000',
        tertiary: '#f5ffc3',
        'on-secondary': '#525151',
        'primary-fixed-dim': '#efc900',
        'tertiary-container': '#def76f',
        'surface-bright': '#2c2c2c',
        'error-container': '#b92902',
        'inverse-surface': '#fcf9f8',
        'tertiary-fixed-dim': '#d5ee68',
        'on-tertiary-fixed': '#414d00',
        'surface-variant': '#262626',
        'surface-container-low': '#131313',
        background: '#0e0e0e',
        'surface-tint': '#ffe792',
        'primary-dim': '#efc900',
        'on-secondary-fixed': '#403f3f',
        'tertiary-dim': '#d5ee68',
        error: '#ff7351',
        'on-surface-variant': '#adaaaa',
        'on-secondary-container': '#d2d0cf',
        'surface-container': '#1a1a1a',
        'on-tertiary-container': '#4e5d00',
        primary: '#ffe792',
        'secondary-fixed-dim': '#d6d4d3',
        'on-tertiary': '#566600',
        'secondary-container': '#474746',
        outline: '#767575',
        'on-error-container': '#ffd2c8',
        'secondary-fixed': '#e5e2e1',
        'primary-fixed': '#ffd709',
        'on-primary-container': '#5b4b00',
        'tertiary-fixed': '#e3fd74',
        surface: '#0e0e0e',
        'on-primary-fixed-variant': '#665500',
        'on-tertiary-fixed-variant': '#5b6b00',
        'surface-dim': '#0e0e0e',
        'primary-container': '#ffd709',
        'on-primary-fixed': '#453900',
        'inverse-primary': '#705e00',
        'inverse-on-surface': '#565555',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
} satisfies Config
